openapi: 3.0.0
info:
  title: Outil de réservation de terrain de Badminton
  description: Une API permettant à des utilisateurs de réserver des créneaux pour des terrains de Badminton
  version: 0.0.1
components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
      description: >-
        Enter the token with the `Bearer: ` prefix, e.g. "Bearer abcde12345".
  schemas:
    UserReservations:
      type: object
      properties:
        reservations:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                description: ID de la réservation
              field:
                type: string
                description: Nom du terrain
              date:
                type: string
                format: date
                description: Date de la réservation
              hour:
                type: string
                format: date
                description: Heure de la réservation
    User:
      type: object
      properties:
        users:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                description: ID de l'utilisateur
              pseudo:
                type: string
                description: Pseudo
              password:
                type: string
                description: Mot de passe
    Field:
      type: object
      properties:
        fields:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                description: ID du terrain
              field_name:
                type: string
                description: Nom du terrain
              next_day_avaible:
                type: string
                format: date
                description: Prochaine date à laquel le terrain est disponible
    Token:
      type: object
      properties:
        Token:
          type: string
          description: Token de connection à rajouter dans les autorisations
paths:
  /register:
    post:
      summary: Création d'un compte utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - pseudo
                - password
              properties:
                pseudo:
                  type: string
                  description: Le pseudo de l'utilisateur
                password:
                  type: string
                  description: Le mot de passe de l'utilisateur
      responses:
        '201':
          description: L'utilisateur.ice a été créé.e
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Paramètres incorrects ou manquants
  /login:
    post:
      summary: Connexion à un compte utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - pseudo
                - password
              properties:
                pseudo:
                  type: string
                  description: Le pseudo de l'utilisateur
                password:
                  type: string
                  description: Le mot de passe de l'utilisateur
      responses:
        '200':
          description: L'utilisateur.ice est connecté.e
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Token'
        '400':
          description: Paramètres incorrects ou manquants
  /slots/reservations/{id}:
    post:
      security:
        - Bearer: []
      summary: Reservation d'un créneau de 45 minutes d'une salle
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
            minimum: 0
      responses:
        '201':
          description: La réservation a été créée
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/UserReservations'
    delete:
      security:
        - Bearer: []
      summary: Annulation d'un créneau de 45 minutes d'une salle
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: number
            minimum: 0
      responses:
        '200':
          description: La réservation a été annulée
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/UserReservations'
        '204':
          description: La réservation a été annulée
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/UserReservations'
        '404':
          description: La réservation n'existe pas
        '400':
          description: L'ID fourni est invalide
  /slots/fields/{name}/date/{date}:
    get:
      summary: Voir la liste des créneaux du terrain pour une date donnée
      parameters:
        - name: name
          in: path
          required: true
          description: L'identifiant du terrain
          schema:
            type: string
            minimum: 0
        - name: date
          in: path
          required: true
          description: La date pour laquelle voir les créneaux (au format DD-MM-YYYY)
          schema:
            type: string
            format: date
      responses:
        '200':
          description: La liste des créneaux disponibles pour le terrain à cette date
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/UserReservations'
        '400':
          description: Les paramètres fournis sont invalides (ID ou date)
        '404':
          description: Le terrain ou les créneaux n'existent pas
  /slots/users/reservations:
    get:
      summary: Voir la liste des créneaux réservé de l'utilisateur connecté
      security:
        - Bearer: []
      responses:
        '200':
          description: La liste des réservation de l'utilisateur connecté
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/UserReservations'
        '400':
          description: L'ID fourni est invalide
        '404':
          description: L'utilisateur n'existe pas
  /slots/fields/{date}:
    get:
      summary: Voir la liste des terrains avec leur créneaux disponible pour une date donnée
      parameters:
        - name: date
          in: path
          required: true
          description: La date pour laquelle voir les créneaux (au format YYYY-MM-DD)
          schema:
            type: string
            format: date
      responses:
        '200':
          description: La liste des créneaux de tous les terrains à cette date
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/UserReservations'
        '404':
          description: L'utilisateur n'existe pas
  /fields/{name}/disable:
    put:
      security:
        - Bearer: []
      summary: Rendre un terrain en indisponible pendant 2 jours
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
            minimum: 0
      responses:
        '200':
          description: La disponibilité du terrain a été modifiée
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Field'
        '204':
          description: La disponibilité du terrain a été modifiée
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Field'
        '400':
          description: L'ID fourni est invalide
  /fields/{name}/avaible:
    put:
      security:
        - Bearer: []
      summary: Mettre un terrain indisponible à disponible
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
            minimum: 0
      responses:
        '200':
          description: La disponibilité du terrain a été modifiée
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Field'
        '204':
          description: La disponibilité du terrain a été modifiée
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Field'
        '400':
          description: L'ID fourni est invalide
