openapi: 3.0.0
info:
  title: Outil de réservation de terrain de Badminton
  description: Une API permettant à des utilisateurs de réserver des créneaux pour des terrains de Badminton
  version: 0.0.1
paths: 
  /register:
    post: 
      summary : Création d'un compte utilisateur
      responses:
        "201":
          description: L'utilisateur.ice a été créé.e
  /login:
    post: 
      summary : Connexion à un compte utilisateur
      responses:
        "200":
          description: L'utilisateur.ice est connecté.e
  /reservations:
    post:
      summary : Reservation d'un créneau de 45 minutes d'une salle
      responses:
        "201":
          description: La réservation a été créée
  /reservations/{id}:
    delete: 
      summary : Annulation d'un créneau de 45 minutes d'une salle
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 0
      responses:
        "200":
          description: La réservation a été annulée
        "204":
          description: La réservation a été annulée
        "404":
          description: La réservation n'existe pas
        "400":
          description: L'ID fourni est invalide
  /fields/{id}:
    put:
      summary : Rendre un terrain en disponible/disponible
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 0
      responses:
        "200":
          description: La disponibilité du terrain a été modifiée
        "204":
          description: La disponibilité du terrain a été modifiée
        "400":
          description: L'ID fourni est invalide
    get: 
      summary : Voir la liste des créneaux du terrain
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 0
      responses:
        "200":
          description: La disponibilité du terrain
        "400":
          description: L'ID fourni est invalide
        "404":
          description: Le terrain n'exsite pas
  /users/{id}/reservation:
    get:
      summary : Voir la liste des créneaux réservé d'un utilisateur
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 0
      responses:
        "200":
          description: La liste des réservation d'un utilisateur
        "400":
          description: L'ID fourni est invalide
        "404":
          description: L'utilisateur n'existe pas
  /fields:
    get:
      summary : Voir la liste des terrains avec leur créneaux disponible
      responses:
        "200":
          description: La liste des créneaux de tous les terrains